version: '2'

services:
  ca.org1.nhsolution.com:
    image: hyperledger/fabric-ca:1.2.1
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: 10m
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.nhsolution.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.nhsolution.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/71997a351dbc8991f3f3feedb8befc6a4276506772533bdb39bfd28b6c6afbd0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.nhsolution.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.nhsolution.com
    
  orderer.nhsolution.com:
    container_name: orderer.nhsolution.com
    image: hyperledger/fabric-orderer:1.2.1
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: 10m
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/nhsolution.com/orderers/orderer.nhsolution.com/msp:/etc/hyperledger/msp/orderer/msp
    
  peer0.org1.nhsolution.com:
    container_name: peer0.org1.nhsolution.com
    image: hyperledger/fabric-peer:1.2.1
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: 10m
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.nhsolution.com
      - CORE_PEER_ADDRESS=peer0.org1.nhsolution.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.nhsolution.com/peers/peer0.org1.nhsolution.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.nhsolution.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.nhsolution.com
      - couchdb

  couchdb:
    container_name: couchdb
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: 10m
    image: hyperledger/fabric-couchdb:0.4.10
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

